# fly.toml file generated for crawler-api on 2023-04-14T16:59:44-03:00

app = "crawler-api"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "gru"
processes = []

[[services]]
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 5000

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
